backend:
  name: git-gateway
  branch: master
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Caption", name: "imageAlt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail", name: "thumbnailimage", widget: "image"}
      - {label: "Services", name: "services", widget: "list"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Additional Image", name: "addlimage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Link to Project", name: "linktoproject", widget: "string"}
      - {label: "Title Tag", name: "titleTag", widget: "string"}
      - {label: "Meta Description", name: "metaDescription", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}